/*
AUTOR: JESÚS MARÍA CALDERÓN CRESPO
GITHUB: http://www.github.com/Jeluchu
WEB: https://jeluchu.github.io
*/

/*
PRIMARY KEY

CLIENTES (DNI)
TIENDAS (NOMBRE)
OPERADORAS (NOMBRE)
TARIFAS(NOMBRE, NOMBRE_OPERADORAS)
MÓVILES (MODELO, MARCA)
*/

/* ELIMINAR LA BASE DE DATOS SI ESXISTE, CREARLA Y USARLA */
DROP DATABASE IF EXISTS ACTORES;
CREATE DATABASE ACTORES;
USE ACTORES;

/* CREAMOS LAS TABLAS CON SUS VARIABLES */
CREATE TABLE ACTORES(
    Codigo INT(10),
    Nombre VARCHAR(20)
    Fecha DATE,
    Nacionalidad VARCHAR(20),
    PRIMARY KEY (Codigo)
);

CREATE TABLE PERSONAJES(
    Codigo INT(10),
    Nombre VARCHAR(20),
    Grado VARCHAR(20),
    Codigo_ACTORES INT(10),
    CodigoSuperior_PERSONAJES INT(10),
    Nacionalidad VARCHAR(20),
    PRIMARY KEY (Codigo),
    FOREIGN KEY (Codigo_ACTORES)
    REFERENCES ACTORES(Codigo),
    FOREIGN KEY (CodigoSuperior_PERSONAJES)
    REFERENCES PERSONAJES(CodigoSuperior)
);

CREATE TABLE PLANETAS(
    Codigo INT(10),
    Galaxia VARCHAR(20)
    Nombre VARCHAR(20),
    PRIMARY KEY (Codigo)
);
