/*
AUTOR: JESÚS MARÍA CALDERÓN CRESPO
GITHUB: http://www.github.com/Jeluchu
WEB: https://jeluchu.github.io
*/

/*
PRIMARY KEY

CLIENTES (DNI)
TIENDAS (NOMBRE)
OPERADORAS (NOMBRE)
TARIFAS(NOMBRE, NOMBRE_OPERADORAS)
MÓVILES (MODELO, MARCA)
*/

/* ELIMINAR LA BASE DE DATOS SI ESXISTE, CREARLA Y USARLA */
DROP DATABASE IF EXISTS MOVILEA;
CREATE DATABASE MOVILEA;
USE MOVILEA;

/* CREAMOS LAS TABLAS CON SUS VARIABLES */
CREATE TABLE CLIENTES(
    DNI CHAR(9),
    NOMBRE VARCHAR(20)
    PRIMER_APELLIDO VARCHAR(20),
    SEGUNDO_APELLIDO VARCHAR(20),
    TELEFONO INT(9),
    E-MAIL VARCHAR(50),
    PRIMARY KEY (DNI)
);

CREATE TABLE TIENDAS(
    NOMBRE VARCHAR(20),
    PROVINCIA VARCHAR(20),
    LOCALIDAD VARCHAR(20),
    DIRECCION VARCHAR(100),
    TELÉFONO INT(9),
    DIAAPERTURA VARCHAR(20),
    DIACIERRE VARCHAR(20),
    HORAAPERTURA TIME,
    HORACIERRE TIME,
    PRIMARY KEY (NOMBRE)
);

CREATE TABLE OPERADORAS(
    NOMBRE VARCHAR(20),
    COLORLOGO VARCHAR(10),
    PORCENTAJECOBERTURA INT(3),
    FRECUENCIAGSM (),
    PAGINAWEB VARCHAR(100)

);

CREATE TABLE TARIFAS(
    NOMBRE VARCHAR(20),
    NOMBRE_OPERADORAS VARCHAR(10),
    TAMAÑODATOS VARCHAR(10),
    TIPODATOS VARCHAR(20),
    MINUTOSGRATIS INT(10),
    SMSGRATIS INT(10),
  );

CREATE TABLE MOVILES(
    MARCA VARCHAR(20),
    MODELO VARCHAR(10),
    DESCRIPCION VARCHAR(10),
    SO VARCHAR(10),
    RAM INT(1),
    PULGADASPANTALLA INT(2),
    CAMARAMPX INT(2),
  );

CREATE TABLE MOVIL_LIBRE(
    MARCA_MOVILES VARCHAR(20),
    MODELO_MOVILES VARCHAR(10),
    NOMBRE_OPERADORAS VARCHAR(10),
    PRECIO VARCHAR(4)
  );

CREATE TABLE MOVIL_CONTRATO(
    MARCA_MOVILES VARCHAR(20),
    MODELO_MOVILES VARCHAR(10),
    NOMBRE_OPERADORAS VARCHAR(10),
    PRECIO VARCHAR(20)
  );

CREATE TABLE OFERTAS(
    NOMBRE_OPERADORAS_TARIFAS VARCHAR(20),
    NOMBRE_TARIFAS VARCHAR(10),
    MARCA_MOVIL_CONTRATO VARCHAR(10),
    MODELO_MOVIL_CONTRATO VARCHAR(20)
  );

CREATE TABLE COMPRAS(
    DNI_CLIENTE VARCHAR(20),
    NOMBRE_TIENDA VARCHAR(10),
    MARCA_MOVILES_LIBRE VARCHAR(10),
    MODELO_MOVIL_LIBRE VARCHAR(20)
    DIA DATE
  );

CREATE TABLE CONTRATOS(
    DNI_CLIENTE VARCHAR(20),
    NOMBRE_TIENDA VARCHAR(10),
    NOMBRE_OPERADORAS_TARIFAS_OFERTAS VARCHAR(20),
    NOMBRE_TARIFAS_OFERTAS VARCHAR(10),
    MARCA_MOVILES_OFERTAS VARCHAR(20),
    MODELO_MOVILES_OFERTAS VARCHAR(20),
    DIA DATE
  );
