/*
AUTOR: JESÚS MARÍA CALDERÓN CRESPO
GITHUB: http://www.github.com/Jeluchu
WEB: https://jeluchu.github.io
*/

/*
PRIMARY KEY

CLIENTES (DNI)
TIENDAS (NOMBRE)
OPERADORAS (NOMBRE)
TARIFAS(NOMBRE, NOMBRE_OPERADORAS)
MÓVILES (MODELO, MARCA)
*/

/* ELIMINAR LA BASE DE DATOS SI ESXISTE, CREARLA Y USARLA */
DROP DATABASE IF EXISTS MOVILEA;
CREATE DATABASE MOVILEA;
USE MOVILEA;

/* CREAMOS LAS TABLAS CON SUS VARIABLES */
CREATE TABLE CLIENTES(
    DNI CHAR(9),
    Nombre VARCHAR(20),
    Primer_Apellido VARCHAR(20),
    Segundo_Apellido VARCHAR(20),
    Telefono INT(9),
    EMail VARCHAR(50),
    PRIMARY KEY (DNI)
);

CREATE TABLE TIENDAS(
    Nombre VARCHAR(20),
    Provincia VARCHAR(20),
    Localidad VARCHAR(20),
    Direccion VARCHAR(100),
    Telefono INT(9),
    DiaApertura VARCHAR(20),
    DiaCierre VARCHAR(20),
    HoraApertura TIMESTAMP,
    HoraCierre TIMESTAMP,
    PRIMARY KEY (NOMBRE)
);

CREATE TABLE OPERADORAS(
<<<<<<< HEAD
    Nombre VARCHAR(20),
    ColorLogo VARCHAR(10),
    PorcentajeCobertura INT(3),
    FrecuenciaGSM VARCHAR(5),
    PaginaWEB VARCHAR(100)
);

CREATE TABLE TARIFAS(
    Nombre VARCHAR(20),
    Nombre_OPERADORAS VARCHAR(10),
    TamanoDatos VARCHAR(10),
    TipoDatos VARCHAR(20),
    MinutosGratis INT(10),
    SMSGratis INT(10),
    FOREIGN KEY (Nombre_OPERADORAS)
    REFERENCES OPERADORAS(Nombre)
  );

CREATE TABLE MOVILES(
    Marca VARCHAR(20),
    Modelo VARCHAR(10),
    Descripcion VARCHAR(10),
    SO VARCHAR(10),
    RAM INT(1),
    PulgadasPantalla INT(2),
    CamaraMPX INT(2),
  );

CREATE TABLE MOVIL_LIBRE(
    Marca_MOVILES VARCHAR(20),
    Modelo_MOVILES VARCHAR(10),
    Precio FLOAT(4),
    FOREIGN KEY (Modelo_MOVILES)
    REFERENCES MOVILES(Modelo)
  );

CREATE TABLE MOVIL_CONTRATO(
    Marca_MOVILES VARCHAR(20),
    Modelo_MOVILES VARCHAR(10),
    Nombre_OPERADORAS VARCHAR(10),
    Precio FLOAT(4),
    FOREIGN KEY (Marca_MOVILES,Modelo_MOVILES)
    REFERENCES MOVILES(Marca,MODELO),
    FOREIGN KEY (Nombre_OPERADORAS)
    REFERENCES OPERADORAS(Nombre)
  );

CREATE TABLE MOVIL_CONTRATO(
    MARCA_MOVILES VARCHAR(20),
    MODELO_MOVILES VARCHAR(10),
    NOMBRE_OPERADORAS VARCHAR(10),
    PRECIO VARCHAR(20)
    FOREIGN KEY (Marca_MOVILES,Modelo_MOVILES)
    REFERENCES MOVILES(Marca,Modelo),
    FOREIGN KEY (Nombre_OPERADORAS)
    REFERENCES OPERADORAS(Nombre)

  );

CREATE TABLE OFERTAS(
    Nombre_OPERADORAS_TARIFAS VARCHAR(20),
    Nombre_TARIFAS VARCHAR(10),
    Marca_MOVIL_CONTRATO VARCHAR(10),
    Modelo_MOVIL_CONTRATO VARCHAR(20)
  );

CREATE TABLE COMPRAS(
    DNI_CLIENTE VARCHAR(20),
    Nombre_TIENDA VARCHAR(10),
    Marca_MOVILES_LIBRE VARCHAR(10),
    Modelo_MOVIL_LIBRE VARCHAR(20)
    Dia DATE
  );

CREATE TABLE CONTRATOS(
    DNI_CLIENTE VARCHAR(20),
    Nombre_TIENDA VARCHAR(10),
    Nombre_OPERADORAS_TARIFAS_OFERTAS VARCHAR(20),
    Nombre_TARIFAS_OFERTAS VARCHAR(10),
    Marca_MOVILES_OFERTAS VARCHAR(20),
    Modelo_MOVILES_OFERTAS VARCHAR(20),
    Dia DATE
  );
