CREATE TABLE SOCIOS(
	NOMBRE VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(30),
	NUMERO_TELEFONO VARCHAR(15),
	FECHA_INSCRIPCION DATE,
	N_SOCIO INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE LIBROS(
	TITULO VARCHAR(30) NOT NULL,
	AUTO VARCHAR(20),
	FECHA_EDITADO DATE,
	N_LIBRO BIGINT AUTO_INCREMENT,
	PRIMARY KEY(N_LIBRO)
);

CREATE TABLE PRESTAMOS(
	FECHA_RETIRO DATE,
	FECHA_ENTREGA DATE,
	N_SOCIO INT,
	N_LIBRO BIGINT,
	IDPRESTAMO BIGINT AUTO_INCREMENT,
	PRIMARY KEY(IDEPRESTAMO)
);

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_SOCIO FOREIGN KEY (N_SOCIO) REFERENCES SOCIOS(N_SOCIO);
ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_LIBRO FOREIGN KEY (N_LIBRO) REFERENCES LIBRO(N_LIBRO);

SELECT IDPRESTAMO AS 'Orden de Prestamos', N_SOCIO, N_LIBRO FROM PRESTAMOS LIMIT 2;
