DROP DATABASE IF EXISTS PRUEBA;
CREATE DATABASE PRUEBA;
USE PRUEBA;

CREATE TABLE tab1 (
	col1 INTEGER(5),
	col2 CHAR(25) NOT NULL,
	col3 INT,
	col4 VARCHAR(10),
	PRIMARY KEY (col1),
	CONSTRAINT FK_COL3 FOREIGN KEY(col3)
	REFERENCES tab2(fil1),
	CONSTRAINT fk_2 FOREIGN KEY(col4)
	REFERENCES tab2(fil1)
);

CREATE TABLE tab2 (
	fil1 INTEGER(5),
	fil2 CHAR(25) NOT NULL,
	fil3 INT,
	fil4 VARCHAR(10),
	PRIMARY KEY (fil1)
);
