DROP DATABASE IF EXISTS Tienda;
CREATE DATABASE Tienda;
USE Tienda;

CREATE TABLE PERSONA (
    Nombre VARCHAR(20) NOT NULL,
    Primer_Apellido VARCHAR(20) NOT NULL,
    Segundo_Apellido VARCHAR(20) NOT NULL,
    Edad TINYINT unsigned NOT NULL,
    Fecha_Nacimiento DATE NOT NULL,
    PRIMARY KEY (Nombre, Primer_Apellido, Segundo_Apellido)
 )ENGINE=InnoDB;


CREATE TABLE PRODUCTO (
    ID INT AUTO_INCREMENT NOT NULL,
    Nombre VARCHAR(20) NOT NULL,
    Descripción TEXT(6000) NOT NULL,
    Imagen VARCHAR(255) NOT NULL,
    Precio FLOAT NOT NULL,
    PRIMARY KEY (ID)
    )ENGINE=InnoDB;

CREATE TABLE PEDIDOS (
    Nombre_PERSONA VARCHAR(20) NOT NULL,
    Primer_Apellido_PERSONA VARCHAR(20) NOT NULL,
    Segundo_Apellido_PERSONA VARCHAR(20) NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    Cantidad INT NOT NULL
)ENGINE=InnoDB;
