/*
AUTOR: JESÚS MARÍA CALDERÓN CRESPO
GITHUB: http://www.github.com/Jeluchu
WEB: https://jeluchu.github.io
*/

/* ELIMINAR LA BASE DE DATOS SI ESXISTE, CREARLA Y USARLA */
DROP DATABASE IF EXISTS Tienda;
CREATE DATABASE Tienda;
USE Tienda;

/* CREAMOS LAS TABLAS CON SUS VARIABLES */
CREATE TABLE PERSONA (
    Nombre VARCHAR(20) ,
    Primer_Apellido VARCHAR(20),
    Segundo_Apellido VARCHAR(20),
    Edad TINYINT unsigned NOT NULL,
    Fecha_Nacimiento DATE NOT NULL,
    PRIMARY KEY (Nombre, Primer_Apellido, Segundo_Apellido)
    );

CREATE TABLE PRODUCTO (
    ID INT AUTO_INCREMENT NOT NULL,
    Nombre VARCHAR(20) NOT NULL,
    Descripción TEXT(6000),
    Imagen VARCHAR(255),
    Precio FLOAT,
    PRIMARY KEY (ID)
    );

CREATE TABLE PEDIDOS (
    Nombre_PERSONA VARCHAR(20),
    Primer_Apellido_PERSONA VARCHAR(20),
    Segundo_Apellido_PERSONA VARCHAR(20),
    ID_PRODUCTO INT AUTO_INCREMENT,
    Cantidad INT,
    FOREIGN KEY (Nombre_PERSONA, Primer_Apellido_PERSONA, Segundo_Apellido_PERSONA)
    REFERENCES PERSONA (Nombre, Primer_Apellido, Segundo_Apellido),
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID)
    );

/* ACTUALIZACIONES DE BASES DE DATOS */
ALTER TABLE PEDIDOS DROP FOREIGN KEY PEDIDOS_ibfk_1;
ALTER TABLE PEDIDOS DROP FOREIGN KEY PEDIDOS_ibfk_2;
ALTER TABLE PERSONA ADD COLUMN DNI CHAR(9);
ALTER TABLE PERSONA MODIFY DNI CHAR(9) FIRST;
ALTER TABLE PERSONA ADD COLUMN Sexo ENUM ('h','m');
ALTER TABLE PERSONA DROP PRIMARY KEY;
ALTER TABLE PEDIDOS DROP COLUMN Nombre_PERSONA;
ALTER TABLE PEDIDOS DROP COLUMN Primer_Apellido_PERSONA;
ALTER TABLE PEDIDOS DROP COLUMN Segundo_Apellido_PERSONA;
ALTER TABLE PERSONA ADD CONSTRAINT PRIMARY KEY (DNI);
ALTER TABLE PEDIDOS ADD FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI);
/* ALTER TABLE PEDIDOS ADD FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI); */

/* INTRODUCE DATOS EN LAS TABLAS */
INSERT INTO PERSONA VALUES ('ERIC','MARTÍN','LEÓN','27','1990-04-05');
INSERT INTO PERSONA VALUES ('JESÚS MARÍA','CALDERÓN','CRESPO','19','1998-12-09');

INSERT INTO PRODUCTO VALUES ('0001','EQUIPO AUDIOVISUAL','MEDIOS DE EQUIPOS DE SONIDO','MEDIA','1000');
INSERT INTO PRODUCTO (Nombre, Descripción, Imagen, Precio) VALUES ('ANIME Y MANGA','ARTÍCULOS DE ANIMACIÓN JAPONESA','MEDIA','200');

INSERT INTO PEDIDOS VALUES ('ERIC','MARTÍN','LEÓN','0001','5');
INSERT INTO PEDIDOS (Nombre_PERSONA, Primer_Apellido_PERSONA, Segundo_Apellido_PERSONA, Cantidad) VALUES ('JESÚS MARÍA','CALDERÓN','CRESPO','20');

INSERT INTO PRODUCTO (Nombre) VALUES('Fernando');



/* MUESTRA LAS TABLAS */
SELECT * FROM PERSONA;
SELECT * FROM PRODUCTO;
SELECT * FROM PEDIDOS;
